name: shop_helper
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  qr_code_scanner: ^1.0.1
  equatable: ^2.0.5
  awesome_extensions: ^2.0.9
  path: ^1.8.3
  uuid: ^4.1.0
  flex_color_scheme: ^7.3.1
  font_awesome_flutter: ^10.5.0
  flutter_animate: ^4.2.0+1
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
